os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 10june_jammy01
      script: 
        - echo "condition with job oneeee"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
